@startuml packages
set namespaceSeparator none
package "zeeguu" as zeeguu #77AADD {
}
package "zeeguu.api" as zeeguu.api #99DDFF {
}
package "zeeguu.api.app" as zeeguu.api.app #99DDFF {
}
package "zeeguu.api.cross_domain_app" as zeeguu.api.cross_domain_app #99DDFF {
}
package "zeeguu.api.custom_fmd_graphs" as zeeguu.api.custom_fmd_graphs #99DDFF {
}
package "zeeguu.api.endpoints" as zeeguu.api.endpoints #99DDFF {
}
package "zeeguu.api.endpoints.accounts" as zeeguu.api.endpoints.accounts #99DDFF {
}
package "zeeguu.api.endpoints.activity_tracking" as zeeguu.api.endpoints.activity_tracking #99DDFF {
}
package "zeeguu.api.endpoints.article" as zeeguu.api.endpoints.article #99DDFF {
}
package "zeeguu.api.endpoints.bookmarks_and_words" as zeeguu.api.endpoints.bookmarks_and_words #99DDFF {
}
package "zeeguu.api.endpoints.exercise_sessions" as zeeguu.api.endpoints.exercise_sessions #99DDFF {
}
package "zeeguu.api.endpoints.exercises" as zeeguu.api.endpoints.exercises #99DDFF {
}
package "zeeguu.api.endpoints.feature_toggles" as zeeguu.api.endpoints.feature_toggles #99DDFF {
}
package "zeeguu.api.endpoints.helpers" as zeeguu.api.endpoints.helpers #99DDFF {
}
package "zeeguu.api.endpoints.helpers.activity_sessions" as zeeguu.api.endpoints.helpers.activity_sessions #99DDFF {
}
package "zeeguu.api.endpoints.nlp" as zeeguu.api.endpoints.nlp #99DDFF {
}
package "zeeguu.api.endpoints.own_texts" as zeeguu.api.endpoints.own_texts #99DDFF {
}
package "zeeguu.api.endpoints.reading_sessions" as zeeguu.api.endpoints.reading_sessions #99DDFF {
}
package "zeeguu.api.endpoints.search" as zeeguu.api.endpoints.search #99DDFF {
}
package "zeeguu.api.endpoints.sessions" as zeeguu.api.endpoints.sessions #99DDFF {
}
package "zeeguu.api.endpoints.speech" as zeeguu.api.endpoints.speech #99DDFF {
}
package "zeeguu.api.endpoints.student" as zeeguu.api.endpoints.student #99DDFF {
}
package "zeeguu.api.endpoints.system_languages" as zeeguu.api.endpoints.system_languages #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard" as zeeguu.api.endpoints.teacher_dashboard #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard._common_api_parameters" as zeeguu.api.endpoints.teacher_dashboard._common_api_parameters #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard._only_teachers_decorator" as zeeguu.api.endpoints.teacher_dashboard._only_teachers_decorator #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard._permissions" as zeeguu.api.endpoints.teacher_dashboard._permissions #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard.article_management" as zeeguu.api.endpoints.teacher_dashboard.article_management #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard.cohorts" as zeeguu.api.endpoints.teacher_dashboard.cohorts #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard.general" as zeeguu.api.endpoints.teacher_dashboard.general #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard.helpers" as zeeguu.api.endpoints.teacher_dashboard.helpers #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard.student" as zeeguu.api.endpoints.teacher_dashboard.student #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard.student_exercises" as zeeguu.api.endpoints.teacher_dashboard.student_exercises #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard.student_overviews" as zeeguu.api.endpoints.teacher_dashboard.student_overviews #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard.student_readings" as zeeguu.api.endpoints.teacher_dashboard.student_readings #99DDFF {
}
package "zeeguu.api.endpoints.teacher_dashboard.student_words" as zeeguu.api.endpoints.teacher_dashboard.student_words #99DDFF {
}
package "zeeguu.api.endpoints.topics" as zeeguu.api.endpoints.topics #99DDFF {
}
package "zeeguu.api.endpoints.translation" as zeeguu.api.endpoints.translation #99DDFF {
}
package "zeeguu.api.endpoints.user" as zeeguu.api.endpoints.user #99DDFF {
}
package "zeeguu.api.endpoints.user_article" as zeeguu.api.endpoints.user_article #99DDFF {
}
package "zeeguu.api.endpoints.user_articles" as zeeguu.api.endpoints.user_articles #99DDFF {
}
package "zeeguu.api.endpoints.user_languages" as zeeguu.api.endpoints.user_languages #99DDFF {
}
package "zeeguu.api.endpoints.user_preferences" as zeeguu.api.endpoints.user_preferences #99DDFF {
}
package "zeeguu.api.endpoints.user_statistics" as zeeguu.api.endpoints.user_statistics #99DDFF {
}
package "zeeguu.api.utils" as zeeguu.api.utils #99DDFF {
}
package "zeeguu.api.utils.abort_handling" as zeeguu.api.utils.abort_handling #99DDFF {
}
package "zeeguu.api.utils.feedparser_extensions" as zeeguu.api.utils.feedparser_extensions #99DDFF {
}
package "zeeguu.api.utils.json_result" as zeeguu.api.utils.json_result #99DDFF {
}
package "zeeguu.api.utils.route_wrappers" as zeeguu.api.utils.route_wrappers #99DDFF {
}
package "zeeguu.api.utils.translator" as zeeguu.api.utils.translator #99DDFF {
}
package "zeeguu.cl" as zeeguu.cl #44BB99 {
}
package "zeeguu.config" as zeeguu.config #BBCC33 {
}
package "zeeguu.config.loader" as zeeguu.config.loader #BBCC33 {
}
package "zeeguu.core" as zeeguu.core #AAAA00 {
}
package "zeeguu.core.account_management" as zeeguu.core.account_management #AAAA00 {
}
package "zeeguu.core.account_management.user_account_creation" as zeeguu.core.account_management.user_account_creation #AAAA00 {
}
package "zeeguu.core.bookmark_quality" as zeeguu.core.bookmark_quality #AAAA00 {
}
package "zeeguu.core.bookmark_quality.fit_for_study" as zeeguu.core.bookmark_quality.fit_for_study #AAAA00 {
}
package "zeeguu.core.bookmark_quality.negative_qualities" as zeeguu.core.bookmark_quality.negative_qualities #AAAA00 {
}
package "zeeguu.core.bookmark_quality.positive_qualities" as zeeguu.core.bookmark_quality.positive_qualities #AAAA00 {
}
package "zeeguu.core.bookmark_quality.top_bookmarks_for_user" as zeeguu.core.bookmark_quality.top_bookmarks_for_user #AAAA00 {
}
package "zeeguu.core.constants" as zeeguu.core.constants #AAAA00 {
}
package "zeeguu.core.content_cleaning" as zeeguu.core.content_cleaning #AAAA00 {
}
package "zeeguu.core.content_cleaning.content_cleaner" as zeeguu.core.content_cleaning.content_cleaner #AAAA00 {
}
package "zeeguu.core.content_cleaning.unicode_normalization" as zeeguu.core.content_cleaning.unicode_normalization #AAAA00 {
}
package "zeeguu.core.content_quality" as zeeguu.core.content_quality #AAAA00 {
}
package "zeeguu.core.content_quality.quality_filter" as zeeguu.core.content_quality.quality_filter #AAAA00 {
}
package "zeeguu.core.content_recommender" as zeeguu.core.content_recommender #AAAA00 {
}
package "zeeguu.core.content_recommender.elastic_recommender" as zeeguu.core.content_recommender.elastic_recommender #AAAA00 {
}
package "zeeguu.core.content_retriever" as zeeguu.core.content_retriever #AAAA00 {
}
package "zeeguu.core.content_retriever.article_downloader" as zeeguu.core.content_retriever.article_downloader #AAAA00 {
}
package "zeeguu.core.content_retriever.crawler_exceptions" as zeeguu.core.content_retriever.crawler_exceptions #AAAA00 {
}
package "zeeguu.core.content_retriever.parse_with_newspaper" as zeeguu.core.content_retriever.parse_with_newspaper #AAAA00 {
}
package "zeeguu.core.content_retriever.parse_with_readability_server" as zeeguu.core.content_retriever.parse_with_readability_server #AAAA00 {
}
package "zeeguu.core.content_retriever.video_dowloader" as zeeguu.core.content_retriever.video_dowloader #AAAA00 {
}
package "zeeguu.core.crowd_translations" as zeeguu.core.crowd_translations #AAAA00 {
}
package "zeeguu.core.definition_of_learned" as zeeguu.core.definition_of_learned #AAAA00 {
}
package "zeeguu.core.definition_of_learned.is_learned" as zeeguu.core.definition_of_learned.is_learned #AAAA00 {
}
package "zeeguu.core.elastic" as zeeguu.core.elastic #AAAA00 {
}
package "zeeguu.core.elastic.elastic_query_builder" as zeeguu.core.elastic.elastic_query_builder #AAAA00 {
}
package "zeeguu.core.elastic.indexing" as zeeguu.core.elastic.indexing #AAAA00 {
}
package "zeeguu.core.elastic.settings" as zeeguu.core.elastic.settings #AAAA00 {
}
package "zeeguu.core.emailer" as zeeguu.core.emailer #AAAA00 {
}
package "zeeguu.core.emailer.password_reset" as zeeguu.core.emailer.password_reset #AAAA00 {
}
package "zeeguu.core.emailer.user_activity" as zeeguu.core.emailer.user_activity #AAAA00 {
}
package "zeeguu.core.emailer.zeeguu_mailer" as zeeguu.core.emailer.zeeguu_mailer #AAAA00 {
}
package "zeeguu.core.exercises" as zeeguu.core.exercises #AAAA00 {
}
package "zeeguu.core.exercises.similar_words" as zeeguu.core.exercises.similar_words #AAAA00 {
}
package "zeeguu.core.feed_handler" as zeeguu.core.feed_handler #AAAA00 {
}
package "zeeguu.core.feed_handler.feed_handler" as zeeguu.core.feed_handler.feed_handler #AAAA00 {
}
package "zeeguu.core.feed_handler.newspaperfeed" as zeeguu.core.feed_handler.newspaperfeed #AAAA00 {
}
package "zeeguu.core.feed_handler.rssfeed" as zeeguu.core.feed_handler.rssfeed #AAAA00 {
}
package "zeeguu.core.language" as zeeguu.core.language #AAAA00 {
}
package "zeeguu.core.language.difficulty_estimator_factory" as zeeguu.core.language.difficulty_estimator_factory #AAAA00 {
}
package "zeeguu.core.language.difficulty_estimator_strategy" as zeeguu.core.language.difficulty_estimator_strategy #AAAA00 {
}
package "zeeguu.core.language.strategies" as zeeguu.core.language.strategies #AAAA00 {
}
package "zeeguu.core.language.strategies.cognacy_difficulty_estimator" as zeeguu.core.language.strategies.cognacy_difficulty_estimator #AAAA00 {
}
package "zeeguu.core.language.strategies.cognacy_wh_difficulty_estimator" as zeeguu.core.language.strategies.cognacy_wh_difficulty_estimator #AAAA00 {
}
package "zeeguu.core.language.strategies.default_difficulty_estimator" as zeeguu.core.language.strategies.default_difficulty_estimator #AAAA00 {
}
package "zeeguu.core.language.strategies.flesch_kincaid_difficulty_estimator" as zeeguu.core.language.strategies.flesch_kincaid_difficulty_estimator #AAAA00 {
}
package "zeeguu.core.language.strategies.frequency_difficulty_estimator" as zeeguu.core.language.strategies.frequency_difficulty_estimator #AAAA00 {
}
package "zeeguu.core.language.strategies.word_history_difficulty_estimator" as zeeguu.core.language.strategies.word_history_difficulty_estimator #AAAA00 {
}
package "zeeguu.core.language.strategies.word_rank_difficulty_estimator" as zeeguu.core.language.strategies.word_rank_difficulty_estimator #AAAA00 {
}
package "zeeguu.core.ml_models" as zeeguu.core.ml_models #AAAA00 {
}
package "zeeguu.core.ml_models.paywall_detector" as zeeguu.core.ml_models.paywall_detector #AAAA00 {
}
package "zeeguu.core.ml_models.utils" as zeeguu.core.ml_models.utils #AAAA00 {
}
package "zeeguu.core.model" as zeeguu.core.model #AAAA00 {
}
package "zeeguu.core.model.article" as zeeguu.core.model.article #AAAA00 {
}
package "zeeguu.core.model.article_difficulty_feedback" as zeeguu.core.model.article_difficulty_feedback #AAAA00 {
}
package "zeeguu.core.model.bookmark" as zeeguu.core.model.bookmark #AAAA00 {
}
package "zeeguu.core.model.cohort" as zeeguu.core.model.cohort #AAAA00 {
}
package "zeeguu.core.model.cohort_article_map" as zeeguu.core.model.cohort_article_map #AAAA00 {
}
package "zeeguu.core.model.difficulty_lingo_rank" as zeeguu.core.model.difficulty_lingo_rank #AAAA00 {
}
package "zeeguu.core.model.domain_name" as zeeguu.core.model.domain_name #AAAA00 {
}
package "zeeguu.core.model.exercise" as zeeguu.core.model.exercise #AAAA00 {
}
package "zeeguu.core.model.exercise_outcome" as zeeguu.core.model.exercise_outcome #AAAA00 {
}
package "zeeguu.core.model.exercise_source" as zeeguu.core.model.exercise_source #AAAA00 {
}
package "zeeguu.core.model.feed" as zeeguu.core.model.feed #AAAA00 {
}
package "zeeguu.core.model.language" as zeeguu.core.model.language #AAAA00 {
}
package "zeeguu.core.model.learning_cycle" as zeeguu.core.model.learning_cycle #AAAA00 {
}
package "zeeguu.core.model.localized_topic" as zeeguu.core.model.localized_topic #AAAA00 {
}
package "zeeguu.core.model.personal_copy" as zeeguu.core.model.personal_copy #AAAA00 {
}
package "zeeguu.core.model.search" as zeeguu.core.model.search #AAAA00 {
}
package "zeeguu.core.model.search_filter" as zeeguu.core.model.search_filter #AAAA00 {
}
package "zeeguu.core.model.search_subscription" as zeeguu.core.model.search_subscription #AAAA00 {
}
package "zeeguu.core.model.session" as zeeguu.core.model.session #AAAA00 {
}
package "zeeguu.core.model.sorted_exercise_log" as zeeguu.core.model.sorted_exercise_log #AAAA00 {
}
package "zeeguu.core.model.starred_article" as zeeguu.core.model.starred_article #AAAA00 {
}
package "zeeguu.core.model.teacher" as zeeguu.core.model.teacher #AAAA00 {
}
package "zeeguu.core.model.teacher_cohort_map" as zeeguu.core.model.teacher_cohort_map #AAAA00 {
}
package "zeeguu.core.model.text" as zeeguu.core.model.text #AAAA00 {
}
package "zeeguu.core.model.topic" as zeeguu.core.model.topic #AAAA00 {
}
package "zeeguu.core.model.topic_filter" as zeeguu.core.model.topic_filter #AAAA00 {
}
package "zeeguu.core.model.topic_subscription" as zeeguu.core.model.topic_subscription #AAAA00 {
}
package "zeeguu.core.model.unique_code" as zeeguu.core.model.unique_code #AAAA00 {
}
package "zeeguu.core.model.url" as zeeguu.core.model.url #AAAA00 {
}
package "zeeguu.core.model.user" as zeeguu.core.model.user #AAAA00 {
}
package "zeeguu.core.model.user_activitiy_data" as zeeguu.core.model.user_activitiy_data #AAAA00 {
}
package "zeeguu.core.model.user_article" as zeeguu.core.model.user_article #AAAA00 {
}
package "zeeguu.core.model.user_exercise_session" as zeeguu.core.model.user_exercise_session #AAAA00 {
}
package "zeeguu.core.model.user_language" as zeeguu.core.model.user_language #AAAA00 {
}
package "zeeguu.core.model.user_preference" as zeeguu.core.model.user_preference #AAAA00 {
}
package "zeeguu.core.model.user_reading_session" as zeeguu.core.model.user_reading_session #AAAA00 {
}
package "zeeguu.core.model.user_word" as zeeguu.core.model.user_word #AAAA00 {
}
package "zeeguu.core.model.word_to_study" as zeeguu.core.model.word_to_study #AAAA00 {
}
package "zeeguu.core.nlp_pipeline" as zeeguu.core.nlp_pipeline #AAAA00 {
}
package "zeeguu.core.nlp_pipeline.alignment_errant" as zeeguu.core.nlp_pipeline.alignment_errant #AAAA00 {
}
package "zeeguu.core.nlp_pipeline.automatic_gec_tagging" as zeeguu.core.nlp_pipeline.automatic_gec_tagging #AAAA00 {
}
package "zeeguu.core.nlp_pipeline.confusion_generator" as zeeguu.core.nlp_pipeline.confusion_generator #AAAA00 {
}
package "zeeguu.core.nlp_pipeline.edit_errant" as zeeguu.core.nlp_pipeline.edit_errant #AAAA00 {
}
package "zeeguu.core.nlp_pipeline.reduce_context" as zeeguu.core.nlp_pipeline.reduce_context #AAAA00 {
}
package "zeeguu.core.nlp_pipeline.spacy_wrapper" as zeeguu.core.nlp_pipeline.spacy_wrapper #AAAA00 {
}
package "zeeguu.core.sql" as zeeguu.core.sql #AAAA00 {
}
package "zeeguu.core.sql.learner" as zeeguu.core.sql.learner #AAAA00 {
}
package "zeeguu.core.sql.learner.exercises_history" as zeeguu.core.sql.learner.exercises_history #AAAA00 {
}
package "zeeguu.core.sql.learner.words" as zeeguu.core.sql.learner.words #AAAA00 {
}
package "zeeguu.core.sql.query_building" as zeeguu.core.sql.query_building #AAAA00 {
}
package "zeeguu.core.sql.teacher" as zeeguu.core.sql.teacher #AAAA00 {
}
package "zeeguu.core.sql.teacher.teachers_for_cohort" as zeeguu.core.sql.teacher.teachers_for_cohort #AAAA00 {
}
package "zeeguu.core.test" as zeeguu.core.test #AAAA00 {
}
package "zeeguu.core.test.mocking_the_web" as zeeguu.core.test.mocking_the_web #AAAA00 {
}
package "zeeguu.core.test.model_test_mixin" as zeeguu.core.test.model_test_mixin #AAAA00 {
}
package "zeeguu.core.test.rules" as zeeguu.core.test.rules #AAAA00 {
}
package "zeeguu.core.test.rules.article_rule" as zeeguu.core.test.rules.article_rule #AAAA00 {
}
package "zeeguu.core.test.rules.base_rule" as zeeguu.core.test.rules.base_rule #AAAA00 {
}
package "zeeguu.core.test.rules.bookmark_rule" as zeeguu.core.test.rules.bookmark_rule #AAAA00 {
}
package "zeeguu.core.test.rules.cohort_rule" as zeeguu.core.test.rules.cohort_rule #AAAA00 {
}
package "zeeguu.core.test.rules.exercise_rule" as zeeguu.core.test.rules.exercise_rule #AAAA00 {
}
package "zeeguu.core.test.rules.exercise_session_rule" as zeeguu.core.test.rules.exercise_session_rule #AAAA00 {
}
package "zeeguu.core.test.rules.feed_rule" as zeeguu.core.test.rules.feed_rule #AAAA00 {
}
package "zeeguu.core.test.rules.language_rule" as zeeguu.core.test.rules.language_rule #AAAA00 {
}
package "zeeguu.core.test.rules.outcome_rule" as zeeguu.core.test.rules.outcome_rule #AAAA00 {
}
package "zeeguu.core.test.rules.source_rule" as zeeguu.core.test.rules.source_rule #AAAA00 {
}
package "zeeguu.core.test.rules.text_rule" as zeeguu.core.test.rules.text_rule #AAAA00 {
}
package "zeeguu.core.test.rules.url_rule" as zeeguu.core.test.rules.url_rule #AAAA00 {
}
package "zeeguu.core.test.rules.user_article_rule" as zeeguu.core.test.rules.user_article_rule #AAAA00 {
}
package "zeeguu.core.test.rules.user_exercise_session_rule" as zeeguu.core.test.rules.user_exercise_session_rule #AAAA00 {
}
package "zeeguu.core.test.rules.user_reading_session_rule" as zeeguu.core.test.rules.user_reading_session_rule #AAAA00 {
}
package "zeeguu.core.test.rules.user_rule" as zeeguu.core.test.rules.user_rule #AAAA00 {
}
package "zeeguu.core.test.rules.user_word_rule" as zeeguu.core.test.rules.user_word_rule #AAAA00 {
}
package "zeeguu.core.test.test_article" as zeeguu.core.test.test_article #AAAA00 {
}
package "zeeguu.core.test.test_bookmark" as zeeguu.core.test.test_bookmark #AAAA00 {
}
package "zeeguu.core.test.test_cohort" as zeeguu.core.test.test_cohort #AAAA00 {
}
package "zeeguu.core.test.test_difficulty_estimator_factory" as zeeguu.core.test.test_difficulty_estimator_factory #AAAA00 {
}
package "zeeguu.core.test.test_domain" as zeeguu.core.test.test_domain #AAAA00 {
}
package "zeeguu.core.test.test_feed" as zeeguu.core.test.test_feed #AAAA00 {
}
package "zeeguu.core.test.test_language" as zeeguu.core.test.test_language #AAAA00 {
}
package "zeeguu.core.test.test_localized_topic" as zeeguu.core.test.test_localized_topic #AAAA00 {
}
package "zeeguu.core.test.test_logging" as zeeguu.core.test.test_logging #AAAA00 {
}
package "zeeguu.core.test.test_retrieve_and_compute" as zeeguu.core.test.test_retrieve_and_compute #AAAA00 {
}
package "zeeguu.core.test.test_text" as zeeguu.core.test.test_text #AAAA00 {
}
package "zeeguu.core.test.test_url" as zeeguu.core.test.test_url #AAAA00 {
}
package "zeeguu.core.test.test_user" as zeeguu.core.test.test_user #AAAA00 {
}
package "zeeguu.core.test.test_user_article" as zeeguu.core.test.test_user_article #AAAA00 {
}
package "zeeguu.core.test.test_user_preferences" as zeeguu.core.test.test_user_preferences #AAAA00 {
}
package "zeeguu.core.test.test_user_word" as zeeguu.core.test.test_user_word #AAAA00 {
}
package "zeeguu.core.test.testing_data" as zeeguu.core.test.testing_data #AAAA00 {
}
package "zeeguu.core.test.tests_difficulty_estimator_strategies" as zeeguu.core.test.tests_difficulty_estimator_strategies #AAAA00 {
}
package "zeeguu.core.test.tests_difficulty_estimator_strategies.test_default_difficulty_estimator" as zeeguu.core.test.tests_difficulty_estimator_strategies.test_default_difficulty_estimator #AAAA00 {
}
package "zeeguu.core.test.tests_difficulty_estimator_strategies.test_flesch_kincaid_difficulty_estimator" as zeeguu.core.test.tests_difficulty_estimator_strategies.test_flesch_kincaid_difficulty_estimator #AAAA00 {
}
package "zeeguu.core.test.tests_difficulty_estimator_strategies.test_frequency_difficulty_estimator" as zeeguu.core.test.tests_difficulty_estimator_strategies.test_frequency_difficulty_estimator #AAAA00 {
}
package "zeeguu.core.user_activity_hooks" as zeeguu.core.user_activity_hooks #AAAA00 {
}
package "zeeguu.core.user_activity_hooks.article_interaction_hooks" as zeeguu.core.user_activity_hooks.article_interaction_hooks #AAAA00 {
}
package "zeeguu.core.user_statistics" as zeeguu.core.user_statistics #AAAA00 {
}
package "zeeguu.core.user_statistics.activity" as zeeguu.core.user_statistics.activity #AAAA00 {
}
package "zeeguu.core.user_statistics.exercise_corectness" as zeeguu.core.user_statistics.exercise_corectness #AAAA00 {
}
package "zeeguu.core.user_statistics.exercise_sessions" as zeeguu.core.user_statistics.exercise_sessions #AAAA00 {
}
package "zeeguu.core.user_statistics.reading_sessions" as zeeguu.core.user_statistics.reading_sessions #AAAA00 {
}
package "zeeguu.core.user_statistics.student_overview" as zeeguu.core.user_statistics.student_overview #AAAA00 {
}
package "zeeguu.core.util" as zeeguu.core.util #AAAA00 {
}
package "zeeguu.core.util.encoding" as zeeguu.core.util.encoding #AAAA00 {
}
package "zeeguu.core.util.hash" as zeeguu.core.util.hash #AAAA00 {
}
package "zeeguu.core.util.text" as zeeguu.core.util.text #AAAA00 {
}
package "zeeguu.core.util.time" as zeeguu.core.util.time #AAAA00 {
}
package "zeeguu.core.util.timer_logging_decorator" as zeeguu.core.util.timer_logging_decorator #AAAA00 {
}
package "zeeguu.core.word_scheduling" as zeeguu.core.word_scheduling #AAAA00 {
}
package "zeeguu.core.word_scheduling.basicSR" as zeeguu.core.word_scheduling.basicSR #AAAA00 {
}
package "zeeguu.core.word_scheduling.basicSR.basicSR" as zeeguu.core.word_scheduling.basicSR.basicSR #AAAA00 {
}
package "zeeguu.core.word_stats" as zeeguu.core.word_stats #AAAA00 {
}
package "zeeguu.logging" as zeeguu.logging #EEDD88 {
}
zeeguu.api.app --> zeeguu
zeeguu.api.app --> zeeguu.api.endpoints
zeeguu.api.app --> zeeguu.config.loader
zeeguu.api.app --> zeeguu.core.model
zeeguu.api.app --> zeeguu.logging
zeeguu.api.custom_fmd_graphs --> zeeguu.core.model
zeeguu.api.endpoints --> zeeguu.api.endpoints.nlp
zeeguu.api.endpoints --> zeeguu.api.endpoints.reading_sessions
zeeguu.api.endpoints --> zeeguu.api.endpoints.student
zeeguu.api.endpoints --> zeeguu.api.endpoints.teacher_dashboard
zeeguu.api.endpoints --> zeeguu.core
zeeguu.api.endpoints.accounts --> zeeguu.api.endpoints.sessions
zeeguu.api.endpoints.accounts --> zeeguu.api.utils.abort_handling
zeeguu.api.endpoints.accounts --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.accounts --> zeeguu.core.account_management.user_account_creation
zeeguu.api.endpoints.accounts --> zeeguu.core.emailer.password_reset
zeeguu.api.endpoints.accounts --> zeeguu.core.model
zeeguu.api.endpoints.accounts --> zeeguu.core.model.unique_code
zeeguu.api.endpoints.accounts --> zeeguu.logging
zeeguu.api.endpoints.activity_tracking --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.activity_tracking --> zeeguu.core.emailer.zeeguu_mailer
zeeguu.api.endpoints.activity_tracking --> zeeguu.core.model
zeeguu.api.endpoints.activity_tracking --> zeeguu.core.user_activity_hooks.article_interaction_hooks
zeeguu.api.endpoints.article --> zeeguu.api.utils
zeeguu.api.endpoints.article --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.article --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.article --> zeeguu.core.model
zeeguu.api.endpoints.article --> zeeguu.core.model.article
zeeguu.api.endpoints.article --> zeeguu.core.model.personal_copy
zeeguu.api.endpoints.bookmarks_and_words --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.bookmarks_and_words --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.bookmarks_and_words --> zeeguu.core.bookmark_quality
zeeguu.api.endpoints.bookmarks_and_words --> zeeguu.core.model
zeeguu.api.endpoints.exercise_sessions --> zeeguu.api.endpoints.helpers.activity_sessions
zeeguu.api.endpoints.exercise_sessions --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.exercise_sessions --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.exercise_sessions --> zeeguu.core.emailer.user_activity
zeeguu.api.endpoints.exercise_sessions --> zeeguu.core.model
zeeguu.api.endpoints.exercises --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.exercises --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.exercises --> zeeguu.core.exercises.similar_words
zeeguu.api.endpoints.exercises --> zeeguu.core.model
zeeguu.api.endpoints.feature_toggles --> zeeguu.api.endpoints
zeeguu.api.endpoints.feature_toggles --> zeeguu.api.utils
zeeguu.api.endpoints.nlp --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.nlp --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.nlp --> zeeguu.core.nlp_pipeline
zeeguu.api.endpoints.own_texts --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.own_texts --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.own_texts --> zeeguu.core.model
zeeguu.api.endpoints.own_texts --> zeeguu.core.model.personal_copy
zeeguu.api.endpoints.reading_sessions --> zeeguu.api.endpoints.helpers.activity_sessions
zeeguu.api.endpoints.reading_sessions --> zeeguu.api.utils
zeeguu.api.endpoints.reading_sessions --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.search --> zeeguu
zeeguu.api.endpoints.search --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.search --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.search --> zeeguu.core.content_recommender
zeeguu.api.endpoints.search --> zeeguu.core.model.search
zeeguu.api.endpoints.search --> zeeguu.core.model.search_filter
zeeguu.api.endpoints.search --> zeeguu.core.model.search_subscription
zeeguu.api.endpoints.search --> zeeguu.core.model.user_article
zeeguu.api.endpoints.search --> zeeguu.logging
zeeguu.api.endpoints.sessions --> zeeguu.api.utils.abort_handling
zeeguu.api.endpoints.sessions --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.sessions --> zeeguu.core.model
zeeguu.api.endpoints.speech --> zeeguu.api.endpoints
zeeguu.api.endpoints.speech --> zeeguu.api.utils
zeeguu.api.endpoints.speech --> zeeguu.core
zeeguu.api.endpoints.speech --> zeeguu.core.model
zeeguu.api.endpoints.student --> zeeguu.api.utils
zeeguu.api.endpoints.student --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.student --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.student --> zeeguu.core.model
zeeguu.api.endpoints.system_languages --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.system_languages --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard --> zeeguu.api.endpoints.student
zeeguu.api.endpoints.teacher_dashboard --> zeeguu.api.endpoints.teacher_dashboard.article_management
zeeguu.api.endpoints.teacher_dashboard --> zeeguu.api.endpoints.teacher_dashboard.cohorts
zeeguu.api.endpoints.teacher_dashboard --> zeeguu.api.endpoints.teacher_dashboard.general
zeeguu.api.endpoints.teacher_dashboard --> zeeguu.api.endpoints.teacher_dashboard.student_exercises
zeeguu.api.endpoints.teacher_dashboard --> zeeguu.api.endpoints.teacher_dashboard.student_overviews
zeeguu.api.endpoints.teacher_dashboard --> zeeguu.api.endpoints.teacher_dashboard.student_readings
zeeguu.api.endpoints.teacher_dashboard --> zeeguu.api.endpoints.teacher_dashboard.student_words
zeeguu.api.endpoints.teacher_dashboard._common_api_parameters --> zeeguu.api.endpoints.teacher_dashboard._permissions
zeeguu.api.endpoints.teacher_dashboard._common_api_parameters --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard._common_api_parameters --> zeeguu.core.sql.query_building
zeeguu.api.endpoints.teacher_dashboard._only_teachers_decorator --> zeeguu.api.endpoints.teacher_dashboard._permissions
zeeguu.api.endpoints.teacher_dashboard._permissions --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard.article_management --> zeeguu.api.endpoints.teacher_dashboard._only_teachers_decorator
zeeguu.api.endpoints.teacher_dashboard.article_management --> zeeguu.api.endpoints.teacher_dashboard._permissions
zeeguu.api.endpoints.teacher_dashboard.article_management --> zeeguu.api.utils.abort_handling
zeeguu.api.endpoints.teacher_dashboard.article_management --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.teacher_dashboard.article_management --> zeeguu.core
zeeguu.api.endpoints.teacher_dashboard.article_management --> zeeguu.core.emailer.zeeguu_mailer
zeeguu.api.endpoints.teacher_dashboard.article_management --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard.article_management --> zeeguu.core.model.cohort_article_map
zeeguu.api.endpoints.teacher_dashboard.cohorts --> zeeguu.api.endpoints.teacher_dashboard._common_api_parameters
zeeguu.api.endpoints.teacher_dashboard.cohorts --> zeeguu.api.endpoints.teacher_dashboard._only_teachers_decorator
zeeguu.api.endpoints.teacher_dashboard.cohorts --> zeeguu.api.endpoints.teacher_dashboard._permissions
zeeguu.api.endpoints.teacher_dashboard.cohorts --> zeeguu.api.endpoints.teacher_dashboard.helpers
zeeguu.api.endpoints.teacher_dashboard.cohorts --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.teacher_dashboard.cohorts --> zeeguu.core
zeeguu.api.endpoints.teacher_dashboard.cohorts --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard.cohorts --> zeeguu.core.model.user_reading_session
zeeguu.api.endpoints.teacher_dashboard.general --> zeeguu.api.endpoints.teacher_dashboard._only_teachers_decorator
zeeguu.api.endpoints.teacher_dashboard.general --> zeeguu.api.endpoints.teacher_dashboard._permissions
zeeguu.api.endpoints.teacher_dashboard.general --> zeeguu.api.endpoints.teacher_dashboard.helpers
zeeguu.api.endpoints.teacher_dashboard.general --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.teacher_dashboard.general --> zeeguu.core
zeeguu.api.endpoints.teacher_dashboard.general --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard.helpers --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard.helpers --> zeeguu.core.sql.teacher.teachers_for_cohort
zeeguu.api.endpoints.teacher_dashboard.helpers --> zeeguu.core.user_statistics.exercise_corectness
zeeguu.api.endpoints.teacher_dashboard.helpers --> zeeguu.core.user_statistics.exercise_sessions
zeeguu.api.endpoints.teacher_dashboard.helpers --> zeeguu.core.user_statistics.reading_sessions
zeeguu.api.endpoints.teacher_dashboard.student --> zeeguu.api.endpoints.teacher_dashboard._common_api_parameters
zeeguu.api.endpoints.teacher_dashboard.student --> zeeguu.api.endpoints.teacher_dashboard._only_teachers_decorator
zeeguu.api.endpoints.teacher_dashboard.student --> zeeguu.api.endpoints.teacher_dashboard._permissions
zeeguu.api.endpoints.teacher_dashboard.student --> zeeguu.api.endpoints.teacher_dashboard.helpers
zeeguu.api.endpoints.teacher_dashboard.student --> zeeguu.api.utils
zeeguu.api.endpoints.teacher_dashboard.student --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.teacher_dashboard.student --> zeeguu.core
zeeguu.api.endpoints.teacher_dashboard.student --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard.student_exercises --> zeeguu.api.endpoints.teacher_dashboard._common_api_parameters
zeeguu.api.endpoints.teacher_dashboard.student_exercises --> zeeguu.api.utils
zeeguu.api.endpoints.teacher_dashboard.student_exercises --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.teacher_dashboard.student_exercises --> zeeguu.core
zeeguu.api.endpoints.teacher_dashboard.student_exercises --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard.student_exercises --> zeeguu.core.sql.learner.exercises_history
zeeguu.api.endpoints.teacher_dashboard.student_exercises --> zeeguu.core.user_statistics.exercise_corectness
zeeguu.api.endpoints.teacher_dashboard.student_overviews --> zeeguu.api.endpoints.teacher_dashboard._common_api_parameters
zeeguu.api.endpoints.teacher_dashboard.student_overviews --> zeeguu.api.utils
zeeguu.api.endpoints.teacher_dashboard.student_overviews --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.teacher_dashboard.student_overviews --> zeeguu.core
zeeguu.api.endpoints.teacher_dashboard.student_overviews --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard.student_overviews --> zeeguu.core.user_statistics.student_overview
zeeguu.api.endpoints.teacher_dashboard.student_readings --> zeeguu.api.endpoints.teacher_dashboard._common_api_parameters
zeeguu.api.endpoints.teacher_dashboard.student_readings --> zeeguu.api.utils
zeeguu.api.endpoints.teacher_dashboard.student_readings --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.teacher_dashboard.student_readings --> zeeguu.core
zeeguu.api.endpoints.teacher_dashboard.student_readings --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard.student_readings --> zeeguu.core.user_statistics.reading_sessions
zeeguu.api.endpoints.teacher_dashboard.student_words --> zeeguu.api.endpoints.teacher_dashboard._common_api_parameters
zeeguu.api.endpoints.teacher_dashboard.student_words --> zeeguu.api.utils
zeeguu.api.endpoints.teacher_dashboard.student_words --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.teacher_dashboard.student_words --> zeeguu.core
zeeguu.api.endpoints.teacher_dashboard.student_words --> zeeguu.core.model
zeeguu.api.endpoints.teacher_dashboard.student_words --> zeeguu.core.sql.learner.words
zeeguu.api.endpoints.topics --> zeeguu
zeeguu.api.endpoints.topics --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.topics --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.topics --> zeeguu.core.model
zeeguu.api.endpoints.topics --> zeeguu.logging
zeeguu.api.endpoints.translation --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.translation --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.translation --> zeeguu.api.utils.translator
zeeguu.api.endpoints.translation --> zeeguu.core.crowd_translations
zeeguu.api.endpoints.translation --> zeeguu.core.model
zeeguu.api.endpoints.translation --> zeeguu.core.model.user_word
zeeguu.api.endpoints.user --> zeeguu.api.endpoints.feature_toggles
zeeguu.api.endpoints.user --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.user --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.user --> zeeguu.core
zeeguu.api.endpoints.user --> zeeguu.core.emailer.zeeguu_mailer
zeeguu.api.endpoints.user_article --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.user_article --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.user_article --> zeeguu.core.content_retriever
zeeguu.api.endpoints.user_article --> zeeguu.core.model
zeeguu.api.endpoints.user_article --> zeeguu.core.model.article_difficulty_feedback
zeeguu.api.endpoints.user_articles --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.user_articles --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.user_articles --> zeeguu.core.content_recommender
zeeguu.api.endpoints.user_articles --> zeeguu.core.model
zeeguu.api.endpoints.user_languages --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.user_languages --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.user_languages --> zeeguu.core
zeeguu.api.endpoints.user_languages --> zeeguu.core.model.language
zeeguu.api.endpoints.user_languages --> zeeguu.core.model.user_language
zeeguu.api.endpoints.user_preferences --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.user_preferences --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.user_preferences --> zeeguu.core
zeeguu.api.endpoints.user_statistics --> zeeguu.api.utils
zeeguu.api.endpoints.user_statistics --> zeeguu.api.utils.json_result
zeeguu.api.endpoints.user_statistics --> zeeguu.api.utils.route_wrappers
zeeguu.api.endpoints.user_statistics --> zeeguu.core.user_statistics.activity
zeeguu.api.utils --> zeeguu.api.utils.json_result
zeeguu.api.utils --> zeeguu.api.utils.route_wrappers
zeeguu.api.utils.route_wrappers --> zeeguu
zeeguu.api.utils.route_wrappers --> zeeguu.core.model.session
zeeguu.api.utils.route_wrappers --> zeeguu.logging
zeeguu.api.utils.translator --> zeeguu.logging
zeeguu.cl --> zeeguu.api.app
zeeguu.core.account_management.user_account_creation --> zeeguu.core
zeeguu.core.account_management.user_account_creation --> zeeguu.core.emailer.user_activity
zeeguu.core.account_management.user_account_creation --> zeeguu.core.model
zeeguu.core.bookmark_quality --> zeeguu.core.bookmark_quality.negative_qualities
zeeguu.core.bookmark_quality --> zeeguu.core.bookmark_quality.positive_qualities
zeeguu.core.bookmark_quality --> zeeguu.core.bookmark_quality.top_bookmarks_for_user
zeeguu.core.bookmark_quality.fit_for_study --> zeeguu.core.bookmark_quality
zeeguu.core.bookmark_quality.fit_for_study --> zeeguu.core.definition_of_learned
zeeguu.core.bookmark_quality.fit_for_study --> zeeguu.core.model.sorted_exercise_log
zeeguu.core.bookmark_quality.negative_qualities --> zeeguu.core.model.bookmark
zeeguu.core.bookmark_quality.positive_qualities --> zeeguu.core.bookmark_quality.negative_qualities
zeeguu.core.bookmark_quality.positive_qualities --> zeeguu.core.model
zeeguu.core.bookmark_quality.top_bookmarks_for_user --> zeeguu.core
zeeguu.core.bookmark_quality.top_bookmarks_for_user --> zeeguu.core.bookmark_quality
zeeguu.core.bookmark_quality.top_bookmarks_for_user --> zeeguu.core.model
zeeguu.core.content_cleaning --> zeeguu.core.content_cleaning.content_cleaner
zeeguu.core.content_cleaning --> zeeguu.core.content_cleaning.unicode_normalization
zeeguu.core.content_cleaning.content_cleaner --> zeeguu.core
zeeguu.core.content_cleaning.content_cleaner --> zeeguu.core.model
zeeguu.core.content_quality.quality_filter --> zeeguu.core.ml_models
zeeguu.core.content_quality.quality_filter --> zeeguu.core.model
zeeguu.core.content_recommender --> zeeguu.core.content_recommender.elastic_recommender
zeeguu.core.content_recommender.elastic_recommender --> zeeguu.core.elastic.elastic_query_builder
zeeguu.core.content_recommender.elastic_recommender --> zeeguu.core.elastic.settings
zeeguu.core.content_recommender.elastic_recommender --> zeeguu.core.model
zeeguu.core.content_recommender.elastic_recommender --> zeeguu.core.util.timer_logging_decorator
zeeguu.core.content_retriever --> zeeguu.core.content_cleaning
zeeguu.core.content_retriever --> zeeguu.core.content_retriever.parse_with_readability_server
zeeguu.core.content_retriever.article_downloader --> zeeguu
zeeguu.core.content_retriever.article_downloader --> zeeguu.core
zeeguu.core.content_retriever.article_downloader --> zeeguu.core.content_quality.quality_filter
zeeguu.core.content_retriever.article_downloader --> zeeguu.core.content_retriever
zeeguu.core.content_retriever.article_downloader --> zeeguu.core.content_retriever.crawler_exceptions
zeeguu.core.content_retriever.article_downloader --> zeeguu.core.elastic.indexing
zeeguu.core.content_retriever.article_downloader --> zeeguu.core.emailer.zeeguu_mailer
zeeguu.core.content_retriever.article_downloader --> zeeguu.core.model
zeeguu.core.content_retriever.article_downloader --> zeeguu.core.model.article
zeeguu.core.content_retriever.article_downloader --> zeeguu.logging
zeeguu.core.content_retriever.parse_with_readability_server --> zeeguu.core.content_retriever.crawler_exceptions
zeeguu.core.content_retriever.video_dowloader --> zeeguu
zeeguu.core.content_retriever.video_dowloader --> zeeguu.core.constants
zeeguu.core.content_retriever.video_dowloader --> zeeguu.core.elastic.indexing
zeeguu.core.content_retriever.video_dowloader --> zeeguu.core.model
zeeguu.core.crowd_translations --> zeeguu.core.model
zeeguu.core.definition_of_learned --> zeeguu.core.definition_of_learned.is_learned
zeeguu.core.elastic.indexing --> zeeguu.core.elastic.settings
zeeguu.core.elastic.indexing --> zeeguu.core.model
zeeguu.core.elastic.indexing --> zeeguu.core.model.article
zeeguu.core.elastic.indexing --> zeeguu.core.model.difficulty_lingo_rank
zeeguu.core.emailer.password_reset --> zeeguu.core.emailer.zeeguu_mailer
zeeguu.core.emailer.user_activity --> zeeguu.core.emailer.zeeguu_mailer
zeeguu.core.emailer.user_activity --> zeeguu.core.model
zeeguu.core.emailer.user_activity --> zeeguu.core.model.user_activitiy_data
zeeguu.core.emailer.zeeguu_mailer --> zeeguu
zeeguu.core.emailer.zeeguu_mailer --> zeeguu.logging
zeeguu.core.exercises.similar_words --> zeeguu.core.word_stats
zeeguu.core.feed_handler --> zeeguu.core.feed_handler.newspaperfeed
zeeguu.core.feed_handler --> zeeguu.core.feed_handler.rssfeed
zeeguu.core.feed_handler.feed_handler --> zeeguu.core.util.time
zeeguu.core.feed_handler.newspaperfeed --> zeeguu.core.feed_handler.feed_handler
zeeguu.core.feed_handler.newspaperfeed --> zeeguu.logging
zeeguu.core.feed_handler.rssfeed --> zeeguu.core.feed_handler.feed_handler
zeeguu.core.feed_handler.rssfeed --> zeeguu.logging
zeeguu.core.language.difficulty_estimator_factory --> zeeguu.core.language.difficulty_estimator_strategy
zeeguu.core.language.difficulty_estimator_factory --> zeeguu.core.language.strategies.default_difficulty_estimator
zeeguu.core.language.difficulty_estimator_factory --> zeeguu.core.language.strategies.flesch_kincaid_difficulty_estimator
zeeguu.core.language.difficulty_estimator_strategy --> zeeguu.core
zeeguu.core.language.difficulty_estimator_strategy --> zeeguu.core.model
zeeguu.core.language.strategies.cognacy_difficulty_estimator --> zeeguu.core
zeeguu.core.language.strategies.cognacy_difficulty_estimator --> zeeguu.core.constants
zeeguu.core.language.strategies.cognacy_difficulty_estimator --> zeeguu.core.language.difficulty_estimator_strategy
zeeguu.core.language.strategies.cognacy_difficulty_estimator --> zeeguu.core.model
zeeguu.core.language.strategies.cognacy_difficulty_estimator --> zeeguu.core.util.text
zeeguu.core.language.strategies.cognacy_wh_difficulty_estimator --> zeeguu.core
zeeguu.core.language.strategies.cognacy_wh_difficulty_estimator --> zeeguu.core.constants
zeeguu.core.language.strategies.cognacy_wh_difficulty_estimator --> zeeguu.core.language.difficulty_estimator_strategy
zeeguu.core.language.strategies.cognacy_wh_difficulty_estimator --> zeeguu.core.model
zeeguu.core.language.strategies.cognacy_wh_difficulty_estimator --> zeeguu.core.util.text
zeeguu.core.language.strategies.default_difficulty_estimator --> zeeguu.core
zeeguu.core.language.strategies.default_difficulty_estimator --> zeeguu.core.language.difficulty_estimator_strategy
zeeguu.core.language.strategies.default_difficulty_estimator --> zeeguu.core.model
zeeguu.core.language.strategies.flesch_kincaid_difficulty_estimator --> zeeguu.core.language.difficulty_estimator_strategy
zeeguu.core.language.strategies.flesch_kincaid_difficulty_estimator --> zeeguu.core.model
zeeguu.core.language.strategies.flesch_kincaid_difficulty_estimator --> zeeguu.core.util.text
zeeguu.core.language.strategies.frequency_difficulty_estimator --> zeeguu.core
zeeguu.core.language.strategies.frequency_difficulty_estimator --> zeeguu.core.language.difficulty_estimator_strategy
zeeguu.core.language.strategies.frequency_difficulty_estimator --> zeeguu.core.model
zeeguu.core.language.strategies.frequency_difficulty_estimator --> zeeguu.core.util.text
zeeguu.core.language.strategies.word_history_difficulty_estimator --> zeeguu.core
zeeguu.core.language.strategies.word_history_difficulty_estimator --> zeeguu.core.constants
zeeguu.core.language.strategies.word_history_difficulty_estimator --> zeeguu.core.language.difficulty_estimator_strategy
zeeguu.core.language.strategies.word_history_difficulty_estimator --> zeeguu.core.model
zeeguu.core.language.strategies.word_history_difficulty_estimator --> zeeguu.core.util.text
zeeguu.core.language.strategies.word_rank_difficulty_estimator --> zeeguu.core
zeeguu.core.language.strategies.word_rank_difficulty_estimator --> zeeguu.core.language.difficulty_estimator_strategy
zeeguu.core.language.strategies.word_rank_difficulty_estimator --> zeeguu.core.model
zeeguu.core.ml_models --> zeeguu.core.ml_models.paywall_detector
zeeguu.core.ml_models.paywall_detector --> zeeguu.core.ml_models.utils
zeeguu.core.ml_models.utils --> zeeguu.core.model
zeeguu.core.model --> zeeguu
zeeguu.core.model --> zeeguu.core.language
zeeguu.core.model --> zeeguu.core.model.article
zeeguu.core.model --> zeeguu.core.model.article_difficulty_feedback
zeeguu.core.model --> zeeguu.core.model.bookmark
zeeguu.core.model --> zeeguu.core.model.cohort
zeeguu.core.model --> zeeguu.core.model.cohort_article_map
zeeguu.core.model --> zeeguu.core.model.difficulty_lingo_rank
zeeguu.core.model --> zeeguu.core.model.domain_name
zeeguu.core.model --> zeeguu.core.model.exercise
zeeguu.core.model --> zeeguu.core.model.exercise_outcome
zeeguu.core.model --> zeeguu.core.model.exercise_source
zeeguu.core.model --> zeeguu.core.model.feed
zeeguu.core.model --> zeeguu.core.model.localized_topic
zeeguu.core.model --> zeeguu.core.model.personal_copy
zeeguu.core.model --> zeeguu.core.model.search
zeeguu.core.model --> zeeguu.core.model.search_filter
zeeguu.core.model --> zeeguu.core.model.search_subscription
zeeguu.core.model --> zeeguu.core.model.session
zeeguu.core.model --> zeeguu.core.model.teacher
zeeguu.core.model --> zeeguu.core.model.teacher_cohort_map
zeeguu.core.model --> zeeguu.core.model.text
zeeguu.core.model --> zeeguu.core.model.topic
zeeguu.core.model --> zeeguu.core.model.topic_filter
zeeguu.core.model --> zeeguu.core.model.topic_subscription
zeeguu.core.model --> zeeguu.core.model.unique_code
zeeguu.core.model --> zeeguu.core.model.url
zeeguu.core.model --> zeeguu.core.model.user
zeeguu.core.model --> zeeguu.core.model.user_activitiy_data
zeeguu.core.model --> zeeguu.core.model.user_article
zeeguu.core.model --> zeeguu.core.model.user_exercise_session
zeeguu.core.model --> zeeguu.core.model.user_language
zeeguu.core.model --> zeeguu.core.model.user_preference
zeeguu.core.model --> zeeguu.core.model.user_reading_session
zeeguu.core.model --> zeeguu.core.model.user_word
zeeguu.core.model --> zeeguu.core.model.word_to_study
zeeguu.core.model --> zeeguu.core.word_scheduling.basicSR.basicSR
zeeguu.core.model.article --> zeeguu.core.content_quality.quality_filter
zeeguu.core.model.article --> zeeguu.core.content_retriever
zeeguu.core.model.article --> zeeguu.core.elastic.indexing
zeeguu.core.model.article --> zeeguu.core.language.difficulty_estimator_factory
zeeguu.core.model.article --> zeeguu.core.model
zeeguu.core.model.article --> zeeguu.core.model.feed
zeeguu.core.model.article --> zeeguu.core.model.language
zeeguu.core.model.article --> zeeguu.core.model.topic
zeeguu.core.model.article --> zeeguu.core.model.url
zeeguu.core.model.article --> zeeguu.core.model.user
zeeguu.core.model.article --> zeeguu.core.model.user_article
zeeguu.core.model.article --> zeeguu.core.util.encoding
zeeguu.core.model.article_difficulty_feedback --> zeeguu.core
zeeguu.core.model.article_difficulty_feedback --> zeeguu.core.model
zeeguu.core.model.bookmark --> zeeguu
zeeguu.core.model.bookmark --> zeeguu.core.bookmark_quality.fit_for_study
zeeguu.core.model.bookmark --> zeeguu.core.definition_of_learned
zeeguu.core.model.bookmark --> zeeguu.core.model
zeeguu.core.model.bookmark --> zeeguu.core.model.exercise
zeeguu.core.model.bookmark --> zeeguu.core.model.exercise_outcome
zeeguu.core.model.bookmark --> zeeguu.core.model.exercise_source
zeeguu.core.model.bookmark --> zeeguu.core.model.language
zeeguu.core.model.bookmark --> zeeguu.core.model.learning_cycle
zeeguu.core.model.bookmark --> zeeguu.core.model.sorted_exercise_log
zeeguu.core.model.bookmark --> zeeguu.core.model.text
zeeguu.core.model.bookmark --> zeeguu.core.model.user
zeeguu.core.model.bookmark --> zeeguu.core.model.user_word
zeeguu.core.model.bookmark --> zeeguu.core.util.encoding
zeeguu.core.model.bookmark --> zeeguu.core.word_scheduling.basicSR.basicSR
zeeguu.core.model.bookmark --> zeeguu.logging
zeeguu.core.model.cohort --> zeeguu.core
zeeguu.core.model.cohort --> zeeguu.core.model
zeeguu.core.model.cohort --> zeeguu.core.model.language
zeeguu.core.model.cohort --> zeeguu.core.model.teacher_cohort_map
zeeguu.core.model.cohort --> zeeguu.core.model.user
zeeguu.core.model.cohort_article_map --> zeeguu.core.model
zeeguu.core.model.cohort_article_map --> zeeguu.core.model.article
zeeguu.core.model.cohort_article_map --> zeeguu.core.model.cohort
zeeguu.core.model.cohort_article_map --> zeeguu.core.util.encoding
zeeguu.core.model.difficulty_lingo_rank --> zeeguu.core
zeeguu.core.model.difficulty_lingo_rank --> zeeguu.core.model
zeeguu.core.model.difficulty_lingo_rank --> zeeguu.core.model.article
zeeguu.core.model.domain_name --> zeeguu.core
zeeguu.core.model.domain_name --> zeeguu.core.model
zeeguu.core.model.exercise --> zeeguu.core
zeeguu.core.model.exercise --> zeeguu.core.model
zeeguu.core.model.exercise --> zeeguu.core.model.bookmark
zeeguu.core.model.exercise --> zeeguu.core.model.exercise_outcome
zeeguu.core.model.exercise --> zeeguu.core.model.exercise_source
zeeguu.core.model.exercise --> zeeguu.core.model.user_exercise_session
zeeguu.core.model.exercise_outcome --> zeeguu.core
zeeguu.core.model.exercise_outcome --> zeeguu.core.model
zeeguu.core.model.exercise_source --> zeeguu.core
zeeguu.core.model.exercise_source --> zeeguu.core.model
zeeguu.core.model.feed --> zeeguu
zeeguu.core.model.feed --> zeeguu.core.feed_handler
zeeguu.core.model.feed --> zeeguu.core.model
zeeguu.core.model.feed --> zeeguu.core.model.language
zeeguu.core.model.feed --> zeeguu.core.model.url
zeeguu.core.model.feed --> zeeguu.logging
zeeguu.core.model.language --> zeeguu
zeeguu.core.model.language --> zeeguu.core.model
zeeguu.core.model.language --> zeeguu.logging
zeeguu.core.model.localized_topic --> zeeguu.core
zeeguu.core.model.localized_topic --> zeeguu.core.model
zeeguu.core.model.localized_topic --> zeeguu.core.model.language
zeeguu.core.model.localized_topic --> zeeguu.core.model.topic
zeeguu.core.model.personal_copy --> zeeguu
zeeguu.core.model.personal_copy --> zeeguu.core.model
zeeguu.core.model.personal_copy --> zeeguu.core.model.article
zeeguu.core.model.personal_copy --> zeeguu.core.model.user
zeeguu.core.model.search --> zeeguu.core
zeeguu.core.model.search --> zeeguu.core.model
zeeguu.core.model.search_filter --> zeeguu.core
zeeguu.core.model.search_filter --> zeeguu.core.model
zeeguu.core.model.search_filter --> zeeguu.core.model.search
zeeguu.core.model.search_filter --> zeeguu.core.model.user
zeeguu.core.model.search_subscription --> zeeguu.core
zeeguu.core.model.search_subscription --> zeeguu.core.model
zeeguu.core.model.search_subscription --> zeeguu.core.model.search
zeeguu.core.model.search_subscription --> zeeguu.core.model.user
zeeguu.core.model.session --> zeeguu.core
zeeguu.core.model.session --> zeeguu.core.model
zeeguu.core.model.session --> zeeguu.core.model.user
zeeguu.core.model.sorted_exercise_log --> zeeguu.core.definition_of_learned
zeeguu.core.model.starred_article --> zeeguu.core.constants
zeeguu.core.model.starred_article --> zeeguu.core.model
zeeguu.core.model.starred_article --> zeeguu.core.model.language
zeeguu.core.model.teacher --> zeeguu.core
zeeguu.core.model.teacher --> zeeguu.core.model
zeeguu.core.model.teacher --> zeeguu.core.model.teacher_cohort_map
zeeguu.core.model.teacher_cohort_map --> zeeguu.core.model
zeeguu.core.model.teacher_cohort_map --> zeeguu.core.model.cohort
zeeguu.core.model.text --> zeeguu.core
zeeguu.core.model.text --> zeeguu.core.model
zeeguu.core.model.text --> zeeguu.core.model.language
zeeguu.core.model.text --> zeeguu.core.model.url
zeeguu.core.model.text --> zeeguu.core.model.user_word
zeeguu.core.model.text --> zeeguu.core.util
zeeguu.core.model.topic --> zeeguu
zeeguu.core.model.topic --> zeeguu.core.model
zeeguu.core.model.topic --> zeeguu.logging
zeeguu.core.model.topic_filter --> zeeguu.core
zeeguu.core.model.topic_filter --> zeeguu.core.model
zeeguu.core.model.topic_filter --> zeeguu.core.model.topic
zeeguu.core.model.topic_filter --> zeeguu.core.model.user
zeeguu.core.model.topic_subscription --> zeeguu.core
zeeguu.core.model.topic_subscription --> zeeguu.core.model
zeeguu.core.model.topic_subscription --> zeeguu.core.model.topic
zeeguu.core.model.topic_subscription --> zeeguu.core.model.user
zeeguu.core.model.unique_code --> zeeguu.core
zeeguu.core.model.unique_code --> zeeguu.core.model
zeeguu.core.model.url --> zeeguu.core
zeeguu.core.model.url --> zeeguu.core.model
zeeguu.core.model.url --> zeeguu.core.model.domain_name
zeeguu.core.model.user --> zeeguu.core
zeeguu.core.model.user --> zeeguu.core.language.difficulty_estimator_factory
zeeguu.core.model.user --> zeeguu.core.model
zeeguu.core.model.user --> zeeguu.core.model.article
zeeguu.core.model.user --> zeeguu.core.model.bookmark
zeeguu.core.model.user --> zeeguu.core.model.cohort
zeeguu.core.model.user --> zeeguu.core.model.learning_cycle
zeeguu.core.model.user --> zeeguu.core.model.user_article
zeeguu.core.model.user --> zeeguu.core.model.user_preference
zeeguu.core.model.user --> zeeguu.core.model.user_reading_session
zeeguu.core.model.user --> zeeguu.core.sql.query_building
zeeguu.core.model.user --> zeeguu.core.util
zeeguu.core.model.user --> zeeguu.core.word_scheduling.basicSR.basicSR
zeeguu.core.model.user --> zeeguu.logging
zeeguu.core.model.user_activitiy_data --> zeeguu
zeeguu.core.model.user_activitiy_data --> zeeguu.core.constants
zeeguu.core.model.user_activitiy_data --> zeeguu.core.model
zeeguu.core.model.user_activitiy_data --> zeeguu.core.model.user_reading_session
zeeguu.core.model.user_activitiy_data --> zeeguu.logging
zeeguu.core.model.user_article --> zeeguu.core.model
zeeguu.core.model.user_article --> zeeguu.core.model.article_difficulty_feedback
zeeguu.core.model.user_article --> zeeguu.core.model.personal_copy
zeeguu.core.model.user_article --> zeeguu.core.util.encoding
zeeguu.core.model.user_exercise_session --> zeeguu.core
zeeguu.core.model.user_exercise_session --> zeeguu.core.model
zeeguu.core.model.user_exercise_session --> zeeguu.core.model.user
zeeguu.core.model.user_exercise_session --> zeeguu.core.sql.learner.exercises_history
zeeguu.core.model.user_language --> zeeguu.core
zeeguu.core.model.user_language --> zeeguu.core.model
zeeguu.core.model.user_language --> zeeguu.core.model.language
zeeguu.core.model.user_preference --> zeeguu
zeeguu.core.model.user_preference --> zeeguu.core.model
zeeguu.core.model.user_preference --> zeeguu.logging
zeeguu.core.model.user_reading_session --> zeeguu.core
zeeguu.core.model.user_reading_session --> zeeguu.core.constants
zeeguu.core.model.user_reading_session --> zeeguu.core.model
zeeguu.core.model.user_reading_session --> zeeguu.core.util.encoding
zeeguu.core.model.user_word --> zeeguu.core
zeeguu.core.model.user_word --> zeeguu.core.model
zeeguu.core.model.user_word --> zeeguu.core.model.language
zeeguu.core.model.word_to_study --> zeeguu.core
zeeguu.core.model.word_to_study --> zeeguu.core.model
zeeguu.core.model.word_to_study --> zeeguu.core.model.bookmark
zeeguu.core.model.word_to_study --> zeeguu.core.model.language
zeeguu.core.model.word_to_study --> zeeguu.core.model.user
zeeguu.core.nlp_pipeline --> zeeguu.core.nlp_pipeline.automatic_gec_tagging
zeeguu.core.nlp_pipeline --> zeeguu.core.nlp_pipeline.confusion_generator
zeeguu.core.nlp_pipeline --> zeeguu.core.nlp_pipeline.reduce_context
zeeguu.core.nlp_pipeline --> zeeguu.core.nlp_pipeline.spacy_wrapper
zeeguu.core.nlp_pipeline.alignment_errant --> zeeguu.core.nlp_pipeline.edit_errant
zeeguu.core.nlp_pipeline.automatic_gec_tagging --> zeeguu.core.nlp_pipeline.alignment_errant
zeeguu.core.nlp_pipeline.automatic_gec_tagging --> zeeguu.core.nlp_pipeline.spacy_wrapper
zeeguu.core.nlp_pipeline.confusion_generator --> zeeguu.core.nlp_pipeline.automatic_gec_tagging
zeeguu.core.nlp_pipeline.confusion_generator --> zeeguu.core.nlp_pipeline.spacy_wrapper
zeeguu.core.nlp_pipeline.reduce_context --> zeeguu.core.nlp_pipeline.spacy_wrapper
zeeguu.core.sql.learner.exercises_history --> zeeguu.core.sql.query_building
zeeguu.core.sql.learner.words --> zeeguu.core.model
zeeguu.core.sql.learner.words --> zeeguu.core.sql.query_building
zeeguu.core.sql.query_building --> zeeguu.core.model
zeeguu.core.sql.teacher.teachers_for_cohort --> zeeguu.core.sql.query_building
zeeguu.core.test.mocking_the_web --> zeeguu.core.content_retriever.parse_with_readability_server
zeeguu.core.test.model_test_mixin --> zeeguu.api.app
zeeguu.core.test.model_test_mixin --> zeeguu.core.model
zeeguu.core.test.model_test_mixin --> zeeguu.core.test.mocking_the_web
zeeguu.core.test.rules.article_rule --> zeeguu.core.model
zeeguu.core.test.rules.article_rule --> zeeguu.core.test.mocking_the_web
zeeguu.core.test.rules.article_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.article_rule --> zeeguu.core.test.rules.feed_rule
zeeguu.core.test.rules.article_rule --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.rules.article_rule --> zeeguu.core.test.rules.url_rule
zeeguu.core.test.rules.base_rule --> zeeguu.core.model
zeeguu.core.test.rules.bookmark_rule --> zeeguu.core.bookmark_quality
zeeguu.core.test.rules.bookmark_rule --> zeeguu.core.model.bookmark
zeeguu.core.test.rules.bookmark_rule --> zeeguu.core.model.user_word
zeeguu.core.test.rules.bookmark_rule --> zeeguu.core.test.rules.article_rule
zeeguu.core.test.rules.bookmark_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.bookmark_rule --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.rules.bookmark_rule --> zeeguu.core.test.rules.text_rule
zeeguu.core.test.rules.bookmark_rule --> zeeguu.core.test.rules.user_word_rule
zeeguu.core.test.rules.cohort_rule --> zeeguu.core.model.cohort
zeeguu.core.test.rules.cohort_rule --> zeeguu.core.model.teacher_cohort_map
zeeguu.core.test.rules.cohort_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.cohort_rule --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.rules.cohort_rule --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.rules.exercise_rule --> zeeguu.core.model.exercise
zeeguu.core.test.rules.exercise_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.exercise_rule --> zeeguu.core.test.rules.outcome_rule
zeeguu.core.test.rules.exercise_rule --> zeeguu.core.test.rules.source_rule
zeeguu.core.test.rules.exercise_session_rule --> zeeguu.core.model
zeeguu.core.test.rules.exercise_session_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.feed_rule --> zeeguu.core.feed_handler
zeeguu.core.test.rules.feed_rule --> zeeguu.core.model
zeeguu.core.test.rules.feed_rule --> zeeguu.core.test.mocking_the_web
zeeguu.core.test.rules.feed_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.feed_rule --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.rules.feed_rule --> zeeguu.core.test.rules.url_rule
zeeguu.core.test.rules.language_rule --> zeeguu.core.model.language
zeeguu.core.test.rules.language_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.outcome_rule --> zeeguu.core.model.exercise_outcome
zeeguu.core.test.rules.outcome_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.source_rule --> zeeguu.core
zeeguu.core.test.rules.source_rule --> zeeguu.core.model.exercise_source
zeeguu.core.test.rules.source_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.text_rule --> zeeguu.core.model.text
zeeguu.core.test.rules.text_rule --> zeeguu.core.test.rules.article_rule
zeeguu.core.test.rules.text_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.text_rule --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.rules.text_rule --> zeeguu.core.test.rules.url_rule
zeeguu.core.test.rules.url_rule --> zeeguu.core.model.url
zeeguu.core.test.rules.url_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.user_article_rule --> zeeguu.core.model
zeeguu.core.test.rules.user_article_rule --> zeeguu.core.model.user_article
zeeguu.core.test.rules.user_article_rule --> zeeguu.core.test.rules.article_rule
zeeguu.core.test.rules.user_article_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.user_article_rule --> zeeguu.core.test.rules.feed_rule
zeeguu.core.test.rules.user_article_rule --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.rules.user_article_rule --> zeeguu.core.test.rules.url_rule
zeeguu.core.test.rules.user_article_rule --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.rules.user_exercise_session_rule --> zeeguu.core.model.user_exercise_session
zeeguu.core.test.rules.user_exercise_session_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.user_exercise_session_rule --> zeeguu.core.test.rules.cohort_rule
zeeguu.core.test.rules.user_exercise_session_rule --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.rules.user_reading_session_rule --> zeeguu.core.model.user_reading_session
zeeguu.core.test.rules.user_reading_session_rule --> zeeguu.core.test.rules.article_rule
zeeguu.core.test.rules.user_reading_session_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.user_reading_session_rule --> zeeguu.core.test.rules.cohort_rule
zeeguu.core.test.rules.user_rule --> zeeguu.core.model.user
zeeguu.core.test.rules.user_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.user_rule --> zeeguu.core.test.rules.bookmark_rule
zeeguu.core.test.rules.user_rule --> zeeguu.core.test.rules.exercise_rule
zeeguu.core.test.rules.user_rule --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.rules.user_word_rule --> zeeguu.core.model.user_word
zeeguu.core.test.rules.user_word_rule --> zeeguu.core.test.rules.base_rule
zeeguu.core.test.rules.user_word_rule --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.test_article --> zeeguu.core
zeeguu.core.test.test_article --> zeeguu.core.model
zeeguu.core.test.test_article --> zeeguu.core.test.mocking_the_web
zeeguu.core.test.test_article --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_article --> zeeguu.core.test.rules.article_rule
zeeguu.core.test.test_article --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.test_bookmark --> zeeguu.core.bookmark_quality
zeeguu.core.test.test_bookmark --> zeeguu.core.definition_of_learned
zeeguu.core.test.test_bookmark --> zeeguu.core.model
zeeguu.core.test.test_bookmark --> zeeguu.core.model.bookmark
zeeguu.core.test.test_bookmark --> zeeguu.core.model.sorted_exercise_log
zeeguu.core.test.test_bookmark --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_bookmark --> zeeguu.core.test.rules.bookmark_rule
zeeguu.core.test.test_bookmark --> zeeguu.core.test.rules.exercise_rule
zeeguu.core.test.test_bookmark --> zeeguu.core.test.rules.exercise_session_rule
zeeguu.core.test.test_bookmark --> zeeguu.core.test.rules.outcome_rule
zeeguu.core.test.test_bookmark --> zeeguu.core.test.rules.source_rule
zeeguu.core.test.test_bookmark --> zeeguu.core.test.rules.text_rule
zeeguu.core.test.test_bookmark --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.test_cohort --> zeeguu.core
zeeguu.core.test.test_cohort --> zeeguu.core.model.teacher
zeeguu.core.test.test_cohort --> zeeguu.core.model.teacher_cohort_map
zeeguu.core.test.test_cohort --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_cohort --> zeeguu.core.test.rules.cohort_rule
zeeguu.core.test.test_difficulty_estimator_factory --> zeeguu.core.language.difficulty_estimator_factory
zeeguu.core.test.test_difficulty_estimator_factory --> zeeguu.core.language.strategies.default_difficulty_estimator
zeeguu.core.test.test_difficulty_estimator_factory --> zeeguu.core.language.strategies.flesch_kincaid_difficulty_estimator
zeeguu.core.test.test_difficulty_estimator_factory --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_domain --> zeeguu.core.model
zeeguu.core.test.test_domain --> zeeguu.core.model.domain_name
zeeguu.core.test.test_domain --> zeeguu.core.model.url
zeeguu.core.test.test_domain --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_domain --> zeeguu.core.test.rules.url_rule
zeeguu.core.test.test_domain --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.test_feed --> zeeguu.core.content_retriever.article_downloader
zeeguu.core.test.test_feed --> zeeguu.core.feed_handler
zeeguu.core.test.test_feed --> zeeguu.core.model
zeeguu.core.test.test_feed --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_feed --> zeeguu.core.test.rules.feed_rule
zeeguu.core.test.test_language --> zeeguu.core
zeeguu.core.test.test_language --> zeeguu.core.model.language
zeeguu.core.test.test_language --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_language --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.test_language --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.test_localized_topic --> zeeguu.core
zeeguu.core.test.test_localized_topic --> zeeguu.core.model
zeeguu.core.test.test_localized_topic --> zeeguu.core.model.language
zeeguu.core.test.test_localized_topic --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_localized_topic --> zeeguu.core.test.rules.article_rule
zeeguu.core.test.test_localized_topic --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.test_localized_topic --> zeeguu.core.test.rules.url_rule
zeeguu.core.test.test_localized_topic --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.test_logging --> zeeguu.logging
zeeguu.core.test.test_retrieve_and_compute --> zeeguu.core
zeeguu.core.test.test_retrieve_and_compute --> zeeguu.core.content_cleaning.content_cleaner
zeeguu.core.test.test_retrieve_and_compute --> zeeguu.core.content_quality.quality_filter
zeeguu.core.test.test_retrieve_and_compute --> zeeguu.core.content_retriever.article_downloader
zeeguu.core.test.test_retrieve_and_compute --> zeeguu.core.model
zeeguu.core.test.test_retrieve_and_compute --> zeeguu.core.test.mocking_the_web
zeeguu.core.test.test_retrieve_and_compute --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_retrieve_and_compute --> zeeguu.core.test.rules.feed_rule
zeeguu.core.test.test_retrieve_and_compute --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.test_retrieve_and_compute --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.test_text --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_text --> zeeguu.core.test.rules.bookmark_rule
zeeguu.core.test.test_text --> zeeguu.core.test.rules.text_rule
zeeguu.core.test.test_text --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.test_url --> zeeguu.core.model
zeeguu.core.test.test_url --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_url --> zeeguu.core.test.rules.url_rule
zeeguu.core.test.test_user --> zeeguu.core.model
zeeguu.core.test.test_user --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_user --> zeeguu.core.test.rules.bookmark_rule
zeeguu.core.test.test_user --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.test_user_article --> zeeguu.core
zeeguu.core.test.test_user_article --> zeeguu.core.model
zeeguu.core.test.test_user_article --> zeeguu.core.model.user_article
zeeguu.core.test.test_user_article --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_user_article --> zeeguu.core.test.rules.article_rule
zeeguu.core.test.test_user_article --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.test_user_article --> zeeguu.core.test.rules.user_article_rule
zeeguu.core.test.test_user_article --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.test_user_preferences --> zeeguu.core.model
zeeguu.core.test.test_user_preferences --> zeeguu.core.model.user_preference
zeeguu.core.test.test_user_preferences --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_user_preferences --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.test_user_preferences --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.test_user_preferences --> zeeguu.core.test.rules.user_word_rule
zeeguu.core.test.test_user_word --> zeeguu.core.model
zeeguu.core.test.test_user_word --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.test_user_word --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.test_user_word --> zeeguu.core.test.rules.user_word_rule
zeeguu.core.test.testing_data --> zeeguu.core.test.mocking_the_web
zeeguu.core.test.tests_difficulty_estimator_strategies.test_default_difficulty_estimator --> zeeguu.core.language.strategies.default_difficulty_estimator
zeeguu.core.test.tests_difficulty_estimator_strategies.test_default_difficulty_estimator --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.tests_difficulty_estimator_strategies.test_default_difficulty_estimator --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.tests_difficulty_estimator_strategies.test_default_difficulty_estimator --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.tests_difficulty_estimator_strategies.test_flesch_kincaid_difficulty_estimator --> zeeguu.core.language.strategies.flesch_kincaid_difficulty_estimator
zeeguu.core.test.tests_difficulty_estimator_strategies.test_flesch_kincaid_difficulty_estimator --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.tests_difficulty_estimator_strategies.test_flesch_kincaid_difficulty_estimator --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.tests_difficulty_estimator_strategies.test_flesch_kincaid_difficulty_estimator --> zeeguu.core.test.rules.user_rule
zeeguu.core.test.tests_difficulty_estimator_strategies.test_frequency_difficulty_estimator --> zeeguu.core.language.difficulty_estimator_factory
zeeguu.core.test.tests_difficulty_estimator_strategies.test_frequency_difficulty_estimator --> zeeguu.core.test.model_test_mixin
zeeguu.core.test.tests_difficulty_estimator_strategies.test_frequency_difficulty_estimator --> zeeguu.core.test.rules.language_rule
zeeguu.core.test.tests_difficulty_estimator_strategies.test_frequency_difficulty_estimator --> zeeguu.core.test.rules.user_rule
zeeguu.core.user_activity_hooks.article_interaction_hooks --> zeeguu.core.constants
zeeguu.core.user_activity_hooks.article_interaction_hooks --> zeeguu.core.emailer.user_activity
zeeguu.core.user_activity_hooks.article_interaction_hooks --> zeeguu.core.model
zeeguu.core.user_activity_hooks.article_interaction_hooks --> zeeguu.logging
zeeguu.core.user_statistics.activity --> zeeguu.core
zeeguu.core.user_statistics.activity --> zeeguu.core.constants
zeeguu.core.user_statistics.exercise_corectness --> zeeguu.core
zeeguu.core.user_statistics.exercise_corectness --> zeeguu.core.model
zeeguu.core.user_statistics.exercise_sessions --> zeeguu.core
zeeguu.core.user_statistics.exercise_sessions --> zeeguu.core.model
zeeguu.core.user_statistics.reading_sessions --> zeeguu.core
zeeguu.core.user_statistics.reading_sessions --> zeeguu.core.model
zeeguu.core.user_statistics.student_overview --> zeeguu.core
zeeguu.core.user_statistics.student_overview --> zeeguu.core.model
zeeguu.core.user_statistics.student_overview --> zeeguu.core.user_statistics.exercise_corectness
zeeguu.core.user_statistics.student_overview --> zeeguu.core.user_statistics.exercise_sessions
zeeguu.core.user_statistics.student_overview --> zeeguu.core.user_statistics.reading_sessions
zeeguu.core.util --> zeeguu.core.util.encoding
zeeguu.core.util --> zeeguu.core.util.hash
zeeguu.core.util --> zeeguu.core.util.time
zeeguu.core.util.encoding --> zeeguu.core.constants
zeeguu.core.util.text --> zeeguu.core.model
zeeguu.core.util.timer_logging_decorator --> zeeguu.core
zeeguu.core.util.timer_logging_decorator --> zeeguu.core.util.time
zeeguu.core.util.timer_logging_decorator --> zeeguu.logging
zeeguu.core.word_scheduling.basicSR.basicSR --> zeeguu.core.model
zeeguu.core.word_scheduling.basicSR.basicSR --> zeeguu.core.model.learning_cycle
@enduml
